FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

ENV NEXT_TELEMETRY_DISABLED=1

RUN npm ci --no-audit --no-fund

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0"]